export const customStyles = {
  control: (styles) => ({
    ...styles,
    width: "100%",
    maxWidth: "14rem",
    minWidth: "12rem",
    borderRadius: "5px",
    color: "#333",
    fontSize: "0.85rem",
    lineHeight: "1.75rem",
    backgroundColor: "#f8f9fa",
    cursor: "pointer",
    border: "1px solid #ced4da",
    boxShadow: "0px 2px 5px rgba(0,0,0, 0.1)",
    padding: "0.375rem 0.75rem",
    ":hover": {
      border: "1px solid #adb5bd",
      boxShadow: "0px 2px 5px rgba(0,0,0, 0.2)",
    },
  }),
  option: (styles) => ({
    ...styles,
    color: "#495057",
    fontSize: "0.85rem",
    lineHeight: "1.75rem",
    backgroundColor: "#f8f9fa",
    padding: "0.375rem 0.75rem",
    ":hover": {
      backgroundColor: "#e9ecef",
      color: "#495057",
      cursor: "pointer",
    },
  }),
  menu: (styles) => ({
    ...styles,
    backgroundColor: "#f8f9fa",
    maxWidth: "14rem",
    border: "1px solid #ced4da",
    borderRadius: "5px",
    boxShadow: "0px 2px 5px rgba(0,0,0, 0.1)",
    marginTop: "0.5rem",
  }),
  placeholder: (defaultStyles) => ({
    ...defaultStyles,
    color: "#6c757d",
    fontSize: "0.85rem",
    lineHeight: "1.75rem",
  }),
};
